### ISSUE TITLE
Feature request: arena overrun

### ISSUE THREAD

**Issue by aza547** [Talryn/AutoCombatLogger#4]
Hi, I'm the author of [Warcraft Recorder](https://github.com/alexanderkershaw/wow-recorder/), and I'm trying to implement classic arena support. 

On retail we use the "Simple Combat Logger" addon, which has a feature to overrun the logging by 30 secs when in arena to catch trailing events. I find myself in need of similar behaviour on classic as there is no robust "end of arena" event other than the ZONE_CHANGE, which often is getting lost when using ACL due to the flushing of the combat log. 

The code to do this in SCL is here: https://github.com/csutcliff/SimpleCombatLogger/blob/main/Main.lua#L386.

Would you be open to implementing such a mechanism / accepting a PR with it, such that I can advise classic players using WR to install ACL? 

Thanks!

**Comment by Talryn** [comment]
I can add that.  I haven't done arenas or even PvP in a while.  Have you seen any other issues with arena combat logging?

**Comment by aza547** [comment]
Thanks, that would be awesome. I haven't seen any other issues (although my testing has been fairly limited). I've mostly just been using /combatlog given the ZONE_CHANGE issues I mentioned. I'll be sure to report back with how I get on.

**Comment by Talryn** [comment]
I added an option for the delay.  I don't do arena so you may need to test it properly.  It's the latest pre-release.  There is an option to control the delay in seconds if that matters.

**Comment by aza547** [comment]
Thanks! Seems to work great.

![image](https://user-images.githubusercontent.com/32389325/197276845-97aeebe4-4e55-44e6-9dfb-d934beccaa49.png)

**Comment by aza547** [comment]
The 30 secs default is also perfect it seems. 

I'd love to include this in our docs, could you publish a release including this when it suits?

**Comment by Talryn** [comment]
I need to do some more testing but I will try to get a release out soon.

**Comment by aza547** [comment]
Brilliant thanks. I'd also love the same thing for BGs (we also rely on ZONE_CHANGE events that get lost currently. Is that something you'd be up for including also? I'd be happy to contribute a PR.

**Comment by Talryn** [comment]
I added that too.  Need to test the new alpha version.

**Comment by aza547** [comment]
Amazing. Thanks again. I'll take it and let you know how I get on.

**Comment by Talryn** [comment]
Closing as the feature should be available in the latest releases.  Let me know if there are any issues with it or the arena / battleground logging.

**Comment by aza547** [comment]
Just dropping a message to say this seem to work great! Thanks again.

**Comment by Talryn** [comment]
Glad it is working out.  As I said if you see any issues with logging arenas, battlegrounds, or specific ones, please let me know.
